# Generated by Django 3.2.13 on 2022-05-26 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('region', models.TextField(choices=[('牛島', '牛島'), ('伊保木・五軒家', '伊保木・五軒家'), ('室積', '室積'), ('光井', '光井'), ('島田', '島田'), ('浅江', '浅江'), ('三井', '三井'), ('周防', '周防'), ('大和', '大和'), ('光市', '全域'), ('その他地域', 'その他')], verbose_name='地域')),
                ('classification', models.TextField(choices=[('政治', '政治'), ('行政', '行政'), ('企業', '企業'), ('文化', '文化'), ('スポーツ', 'スポーツ'), ('自然', '自然'), ('学校', '学校'), ('人物', '人物'), ('その他', 'その他')], verbose_name='分類')),
                ('post', models.TextField(verbose_name='投稿内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
